version: '3.8'

services:
  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7001:6379"
    networks:
      - redisnet

  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:6379"
    networks:
      - redisnet

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:6379"
    networks:
      - redisnet

  redis-node-4:
    image: redis:7
    container_name: redis-node-4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7004:6379"
    networks:
      - redisnet

  redis-node-5:
    image: redis:7
    container_name: redis-node-5
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7005:6379"
    networks:
      - redisnet

  redis-node-6:
    image: redis:7
    container_name: redis-node-6
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7006:6379"
    networks:
      - redisnet

  redis-cluster-init:
    image: redis:7
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    volumes:
      - ./init-cluster.sh:/init-cluster.sh
    entrypoint: ["bash", "/init-cluster.sh"]
    networks:
      - redisnet

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=node1:redis-node-1:6379,node2:redis-node-2:6379,node3:redis-node-3:6379,node4:redis-node-4:6379,node5:redis-node-5:6379,node6:redis-node-6:6379
    ports:
      - "8889:8081"
    networks:
      - redisnet

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    networks:
      - redisnet
# redis://default@redis-node-1:6379

networks:
  redisnet:
    driver: bridge
