version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 7001:6379
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7001
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 7002:6379
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7002
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 7003:6379
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7003
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 7004:6379
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7004
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 7005:6379
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7005
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 6379:6379
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=6379
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local

networks:
  default:
    name: local_network